syntax = "proto3";

package cpay.api.v1.blockchain;

option go_package = "github.com/cpay-dev/proto-go/api/v1/blockchain";

import "api/v1/blockchain/chain_id.proto";

message Asset {
  string id = 1;
  ChainID chain = 2;
  string name = 3;
  string symbol = 4;
  AssetMetadata metadata = 5;
}

message AssetMetadata {
  string address = 1;
  uint32 decimals = 2;

  oneof metadata {
    AssetMetadataEVM evm = 3;
    AssetMetadataSVM svm = 4;
  }
}

message AssetMetadataEVM {
}

message AssetMetadataSVM {
}
