syntax = "proto3";

package cpay.api.v1.merchant.asset;

option go_package = "github.com/cpay-dev/proto-go/api/v1/merchant/asset";

import "api/v1/merchant/asset/asset.proto";
import "blockchain/v1/chain.proto";

service AssetService {
  rpc ListAssets(ListAssetsRequest) returns (ListAssetsResponse);
  rpc GetAssetPrice(GetAssetPriceRequest) returns (GetAssetPriceResponse);
}

message ListAssetsRequest {
  cpay.blockchain.v1.Chain chain_id = 1;
}

message ListAssetsResponse {
  repeated Asset assets = 1;
}

message GetAssetPriceRequest {
  string asset_id = 1;
}

message GetAssetPriceResponse {
  string price = 1;
}
