syntax = "proto3";

package cpay.blockchain.v1.indexer;

option go_package = "github.com/cpay-dev/proto-go/blockchain/v1/indexer";

import "blockchain/v1/block.proto";
import "blockchain/v1/chain.proto";

message BlockBase {
  cpay.blockchain.v1.Chain chain = 1;
  cpay.blockchain.v1.ConfirmationLevel confirmation_level = 2;
  string block_hash = 3;
  uint64 block_number = 4;
  uint64 block_timestamp = 5;
}

message Block {
  BlockBase base = 1;
  oneof transactions {
    EVMTransactions evm_transactions = 6;
  }
}

message EVMTransactions {
  bytes serialized_txs = 1;
  bytes serialized_receipts = 2;
}
