syntax = "proto3";

package cpay.blockchain.v1.indexer;

option go_package = "github.com/cpay-dev/proto-go/blockchain/v1/indexer";

import "blockchain/v1/indexer/types.proto";

message ParsedBlock {
  Chain chain = 1;
  ConfirmationLevel confirmation_level = 2;
  string block_hash = 3;
  uint64 block_number = 4;
  uint64 block_timestamp = 5;
  repeated ParsedTransfer transfers = 6;
}

message ParsedTransfer {
  string tx_hash = 1;
  string amount = 2;
  string from = 3;
  string to = 4;
  uint64 index = 5;
  oneof kind {
    bool native = 6;
    string contract = 7;
  }
}
