syntax = "proto3";

package cpay.api.v1.merchant;

option go_package = "github.com/cpay-dev/proto-go/api/v1/merchant";

import "api/v1/merchant/payment-intent.proto";

service PaymentIntentService {
  rpc CreatePaymentIntent(CreatePaymentIntentRequest) returns (CreatePaymentIntentResponse);
}

message CreatePaymentIntentRequest {
  string asset_id = 1;
  oneof amount {
    string amount_usd = 2;
    string amount_asset = 3;
  }
}

message CreatePaymentIntentResponse {
  PaymentIntent payment_intent = 1;
}
