syntax = "proto3";

package cpay.api.v1.merchant;

option go_package = "github.com/cpay-dev/proto-go/api/v1/merchant";

import "api/v1/blockchain/asset.proto";
import "api/v1/blockchain/chain.proto";

service MerchantService {
  rpc ListChains(ListChainsRequest) returns (ListChainsResponse);
  rpc ListAssets(ListAssetsRequest) returns (ListAssetsResponse);
}

message ListChainsRequest {
}

message ListChainsResponse {
  repeated blockchain.Chain chains = 1;
}

message ListAssetsRequest {
  blockchain.ChainID chain = 1;
}

message ListAssetsResponse {
  repeated blockchain.Asset assets = 1;
}
